Add project based on milestone
Jahia/jahia-modules-action pull request #168
Opened 2024-12-09 21:45 UTC by Fgerthoffert

- Created an action to add/remove the "Product Releases" based on the presence (or not) of a Milestone
- Added condition to only execute some jobs based on the type of event. For example if we know that a bunch of steps are only performed when labels are added, then this if conditions makes it possible not to execute such jobs.

2024-12-10 09:26 UTC, rknj requested changes

2024-12-10 11:16 UTC, Fgerthoffert commented on add-project-based-on-milestone/action.yml
> +    - name: Check if a Security Jira ticket is already linked, create it if not
Right, thanks

2024-12-11 08:39 UTC, rknj requested changes

2024-12-11 08:39 UTC, rknj commented on delivery/add-project-based-on-milestone/action.yml
> +          const idResp = await github.graphql(
Maybe we could use a more explicit var name?

2024-12-11 11:22 UTC, rknj approved these changes

2024-12-11 14:58 UTC, merged