skip reports in case of no test
Jahia/jahia-modules-action pull request #97
Opened 2023-06-22 09:10 UTC by dgriffon

In case of integration test fail before running the test, we have to skip the reports (they currently fail to execute)

2023-06-22 11:32 UTC, Fgerthoffert requested changes
Do not forge to include the built version in the PR as well

2023-06-22 11:52 UTC, dgriffon commented on integration-tests/src/jahia-reporter/pagerduty.ts
> +    core.info(
Indeed, done, thank you for the review

2023-06-22 13:18 UTC, Fgerthoffert approved these changes

2023-06-25 09:44 UTC, dgriffon commented
Not required, to have a result test if no test are executed, create the required folder on startup fail:
```
end=$((SECONDS+300))
echo " == Waiting for Jahia to startup"
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${JAHIA_URL}/cms/login)" != "200" ]]; do
  if [ $SECONDS -gt $end ]; then
    echo "JAHIA NOT RESPONDING FAILURE - EXITING SCRIPT, NOT RUNNING THE TESTS"
    echo "failure" > ./results/test_failure
    mkdir -p results/xml_reports
    exit 1
  fi
  sleep 5;
done
```

2023-06-25 09:44 UTC, closed without merging